services:
  mqtt_relay:
    container_name: mqtt_relay
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app:ro #everything read-only except all below
      - ./csvs:/app/csvs
    restart: unless-stopped
    stop_signal: SIGINT #faster shutdown
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - mqttnet
networks:
  mqttnet:
    external: true
